### ISSUE TITLE
Unable to deposit AKT to deployment

### ISSUE THREAD

**Issue by piber-dev** [akash-network/support#264]
**Describe the bug**

after creating a deployment, i am unable to deposit AKT

> account address = akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6
> deploy.yaml = https://raw.githubusercontent.com/akash-network/docs/master/guides/deploy/deploy.yml

**To Reproduce**

commands used
```
akash tx deployment create deploy.yml --from $AKASH_KEY_NAME
akash tx deployment deposit 10000uakt --from $AKASH_KEY_NAME --dseq "229949"
```

logs
```
akash tx deployment create deploy.yml --from $AKASH_KEY_NAME
{"body":{"messages":[{"@type":"/akash.deployment.v1beta4.MsgCreateDeployment","id":{"owner":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6","dseq":"229949"},"groups":[{"name":"westcoast","requirements":{"signed_by":{"all_of":[],"any_of":[]},"attributes":[{"key":"host","value":"akash"}]},"resources":[{"resource":{"id":1,"cpu":{"units":{"val":"100"},"attributes":[]},"memory":{"quantity":{"val":"536870912"},"attributes":[]},"storage":[{"name":"default","quantity":{"val":"536870912"},"attributes":[]}],"gpu":{"units":{"val":"0"},"attributes":[]},"endpoints":[{"kind":"SHARED_HTTP","sequence_number":0}]},"count":1,"price":{"denom":"uakt","amount":"1000.000000000000000000"}}]}],"hash":"ZORpdTqmvTDIbJjnEP5Vo9MJ8uVzbYp6mQWJAeD/n8I=","deposit":{"denom":"uakt","amount":"500000"},"depositor":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6"}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"uakt","amount":"2578"}],"gas_limit":"103083","payer":"","granter":""},"tip":null},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
{"height":"229951","txhash":"6A7FE86F02E1616F709EB653D85C5BBE6FA16F57FDEE421A93015D6EA2B55767","codespace":"","code":0,"data":"12370A352F616B6173682E6465706C6F796D656E742E763162657461342E4D73674372656174654465706C6F796D656E74526573706F6E7365","raw_log":"[{\"msg_index\":0,\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"/akash.deployment.v1beta4.MsgCreateDeployment\"},{\"key\":\"sender\",\"value\":\"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6\"},{\"key\":\"module\",\"value\":\"deployment\"}]},{\"type\":\"akash.deployment.v1.EventDeploymentCreated\",\"attributes\":[{\"key\":\"hash\",\"value\":\"\\\"ZORpdTqmvTDIbJjnEP5Vo9MJ8uVzbYp6mQWJAeD/n8I=\\\"\"},{\"key\":\"id\",\"value\":\"{\\\"owner\\\":\\\"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6\\\",\\\"dseq\\\":\\\"229949\\\"}\"}]},{\"type\":\"akash.market.v1.EventOrderCreated\",\"attributes\":[{\"key\":\"id\",\"value\":\"{\\\"owner\\\":\\\"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6\\\",\\\"dseq\\\":\\\"229949\\\",\\\"gseq\\\":1,\\\"oseq\\\":1}\"}]},{\"type\":\"coin_spent\",\"attributes\":[{\"key\":\"spender\",\"value\":\"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6\"},{\"key\":\"amount\",\"value\":\"500000uakt\"}]},{\"type\":\"coin_received\",\"attributes\":[{\"key\":\"receiver\",\"value\":\"akash14pphss726thpwws3yc458hggufynm9x77l4l2u\"},{\"key\":\"amount\",\"value\":\"500000uakt\"}]},{\"type\":\"transfer\",\"attributes\":[{\"key\":\"recipient\",\"value\":\"akash14pphss726thpwws3yc458hggufynm9x77l4l2u\"},{\"key\":\"sender\",\"value\":\"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6\"},{\"key\":\"amount\",\"value\":\"500000uakt\"}]},{\"type\":\"message\",\"attributes\":[{\"key\":\"sender\",\"value\":\"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6\"}]}]}]","logs":[{"msg_index":0,"log":"","events":[{"type":"message","attributes":[{"key":"action","value":"/akash.deployment.v1beta4.MsgCreateDeployment"},{"key":"sender","value":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6"},{"key":"module","value":"deployment"}]},{"type":"akash.deployment.v1.EventDeploymentCreated","attributes":[{"key":"hash","value":"\"ZORpdTqmvTDIbJjnEP5Vo9MJ8uVzbYp6mQWJAeD/n8I=\""},{"key":"id","value":"{\"owner\":\"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6\",\"dseq\":\"229949\"}"}]},{"type":"akash.market.v1.EventOrderCreated","attributes":[{"key":"id","value":"{\"owner\":\"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6\",\"dseq\":\"229949\",\"gseq\":1,\"oseq\":1}"}]},{"type":"coin_spent","attributes":[{"key":"spender","value":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6"},{"key":"amount","value":"500000uakt"}]},{"type":"coin_received","attributes":[{"key":"receiver","value":"akash14pphss726thpwws3yc458hggufynm9x77l4l2u"},{"key":"amount","value":"500000uakt"}]},{"type":"transfer","attributes":[{"key":"recipient","value":"akash14pphss726thpwws3yc458hggufynm9x77l4l2u"},{"key":"sender","value":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6"},{"key":"amount","value":"500000uakt"}]},{"type":"message","attributes":[{"key":"sender","value":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6"}]}]}],"info":"","gas_wanted":"103083","gas_used":"97468","tx":null,"timestamp":"","events":[{"type":"coin_spent","attributes":[{"key":"spender","value":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6","index":true},{"key":"amount","value":"2578uakt","index":true}]},{"type":"coin_received","attributes":[{"key":"receiver","value":"akash17xpfvakm2amg962yls6f84z3kell8c5lazw8j8","index":true},{"key":"amount","value":"2578uakt","index":true}]},{"type":"transfer","attributes":[{"key":"recipient","value":"akash17xpfvakm2amg962yls6f84z3kell8c5lazw8j8","index":true},{"key":"sender","value":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6","index":true},{"key":"amount","value":"2578uakt","index":true}]},{"type":"message","attributes":[{"key":"sender","value":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6","index":true}]},{"type":"tx","attributes":[{"key":"fee","value":"2578uakt","index":true},{"key":"fee_payer","value":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6","index":true}]},{"type":"tx","attributes":[{"key":"acc_seq","value":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6/5","index":true}]},{"type":"tx","attributes":[{"key":"signature","value":"kMxMCkK0eYBc4NxtPoqbWPBlgNKLyPvTDrJ7V9LWhCxsYJyelZVOoKnkq/66gnfe/3O4w19aX5c4ESuJk9HLSQ==","index":true}]},{"type":"message","attributes":[{"key":"action","value":"/akash.deployment.v1beta4.MsgCreateDeployment","index":true},{"key":"sender","value":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6","index":true},{"key":"module","value":"deployment","index":true}]},{"type":"akash.deployment.v1.EventDeploymentCreated","attributes":[{"key":"hash","value":"\"ZORpdTqmvTDIbJjnEP5Vo9MJ8uVzbYp6mQWJAeD/n8I=\"","index":true},{"key":"id","value":"{\"owner\":\"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6\",\"dseq\":\"229949\"}","index":true}]},{"type":"akash.market.v1.EventOrderCreated","attributes":[{"key":"id","value":"{\"owner\":\"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6\",\"dseq\":\"229949\",\"gseq\":1,\"oseq\":1}","index":true}]},{"type":"coin_spent","attributes":[{"key":"spender","value":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6","index":true},{"key":"amount","value":"500000uakt","index":true}]},{"type":"coin_received","attributes":[{"key":"receiver","value":"akash14pphss726thpwws3yc458hggufynm9x77l4l2u","index":true},{"key":"amount","value":"500000uakt","index":true}]},{"type":"transfer","attributes":[{"key":"recipient","value":"akash14pphss726thpwws3yc458hggufynm9x77l4l2u","index":true},{"key":"sender","value":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6","index":true},{"key":"amount","value":"500000uakt","index":true}]},{"type":"message","attributes":[{"key":"sender","value":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6","index":true}]}]}
```

```
akash tx deployment deposit 10000uakt --from $AKASH_KEY_NAME --dseq "229949"
{"body":{"messages":[{"@type":"/akash.deployment.v1.MsgDepositDeployment","id":{"owner":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6","dseq":"229949"},"amount":{"denom":"uakt","amount":"10000"},"depositor":"akash1am43p6tuyrv766a030qgq9ghfa8hfj68fewqf6"}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"uakt","amount":"1892"}],"gas_limit":"75652","payer":"","granter":""},"tip":null},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
panic: expected *legacytx.LegacyMsg when using amino JSON

goroutine 33 [running]:
github.com/cosmos/cosmos-sdk/x/auth/migrations/legacytx.StdSignBytes({0x4000941040, 0x9}, 0xd, 0x6, 0x0, {{0x40014088a0, 0x1, 0x1}, 0x12784, {0x0, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.47.16-ics-lsm/x/auth/migrations/legacytx/stdsign.go:60 +0x38c
github.com/cosmos/cosmos-sdk/x/auth/tx.signModeLegacyAminoJSONHandler.GetSignBytes({}, 0x30?, {{0x4000f565d0, 0x2c}, {0x4000941040, 0x9}, 0xd, 0x6, {0x3680ba8, 0x400148f878}}, ...)
	github.com/cosmos/cosmos-sdk@v0.47.16-ics-lsm/x/auth/tx/legacy_amino_json.go:68 +0x33c
github.com/cosmos/cosmos-sdk/x/auth/signing.SignModeHandlerMap.GetSignBytes({0x1, {0x4000c005b0, 0x3, 0x4}, 0x4000e49b90}, 0x7f, {{0x4000f565d0, 0x2c}, {0x4000941040, 0x9}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.47.16-ics-lsm/x/auth/signing/handler_map.go:59 +0xac
github.com/cosmos/cosmos-sdk/client/tx.Sign({{0x369db50, 0x40003986c0}, {0x3685c80, 0x400089bc80}, {0x36722e8, 0x5034260}, 0xd, 0x6, 0x12784, 0x0, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.47.16-ics-lsm/client/tx/tx.go:308 +0x4e4
pkg.akt.dev/go/node/client/v1beta3.(*serialBroadcaster).buildAndBroadcastTx(_, {_, _}, {{0x369db50, 0x40003986c0}, {0x3685c80, 0x400089bc80}, {0x36722e8, 0x5034260}, 0xd, ...}, ...)
	pkg.akt.dev/go@v0.0.2-rc3/node/client/v1beta3/tx.go:598 +0x330
pkg.akt.dev/go/node/client/v1beta3.(*serialBroadcaster).broadcaster(_, {{0x369db50, 0x40003986c0}, {0x3685c80, 0x400089bc80}, {0x36722e8, 0x5034260}, 0xd, 0x6, 0x0, ...})
	pkg.akt.dev/go@v0.0.2-rc3/node/client/v1beta3/tx.go:508 +0x154
created by pkg.akt.dev/go/node/client/v1beta3.newSerialTx in goroutine 1
	pkg.akt.dev/go@v0.0.2-rc3/node/client/v1beta3/tx.go:293 +0x688
```

Environment: Ubuntu VM on Macbook with akash version v1.0.0-rc9

**Comment by chainzero** [comment]
@piber-dev - verified that this issue is reproducible when using signing mode of `amino-json`.  If the signing mode is change to direct - such as the following - the transaction will succeed in our testing.

```
export AKASH_SIGN_MODE=direct
```

Could you please also confirm that the update of the signing mode cures the issue on your testing as well?

Later versions of the Cosmos SDK have begun deprecating support of signing mode `amino-json` and we will likely make suggestion and update documentation to use signing mode `direct` when this version is released on mainnet.

**Comment by piber-dev** [comment]
hello @chainzero i can confirm that this also makes it possible to test in my environment. if this is starting to be deprecated, i think this issue is resolved and i will close it. thanks you.
