### ISSUE TITLE
Testnet Provider Pods Crashing on Receipt of Order

### ISSUE THREAD

**Issue by chainzero** [akash-network/support#99]
Provider version - 0.3.0-rc6

Issue - on receipt of order and resource reservation the following occur is encountered.  This causes the provider pod to continually restart.

```
I[2023-04-27|13:11:32.015] requesting reservation                       module=bidengine-order cmp=provider order=akash1usm9umrgzckc2pa873cmqwqplr9kuur95mz3v6/268675/1/1
D[2023-04-27|13:11:32.015] reservation requested                        module=provider-cluster cmp=provider cmp=service cmp=inventory-service order=akash1usm9umrgzckc2pa873cmqwqplr9kuur95mz3v6/268675/1/1 resources="group_id:<owner:\"akash1usm9umrgzckc2pa873cmqwqplr9kuur95mz3v6\" dseq:268675 gseq:1 > state:open group_spec:<name:\"akash\" requirements:<signed_by:<> attributes:<key:\"host\" value:\"akash\" > > resources:<resources:<cpu:<units:<val:\"1000\" > > memory:<quantity:<val:\"536870912\" > > storage:<name:\"default\" quantity:<val:\"2147483648\" > > endpoints:<> > count:1 price:<denom:\"uakt\" amount:\"10000000000000000000000\" > > > created_at:268677 "
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x796cc4]

goroutine 134 [running]:
math/big.(*Int).Sub(0xc000fa66c0, 0x16cc167?, 0x1?)
	math/big/int.go:157 +0x24
github.com/cosmos/cosmos-sdk/types.sub(...)
	github.com/cosmos/cosmos-sdk@v0.45.15/types/int.go:29
github.com/cosmos/cosmos-sdk/types.Int.Sub({0x1?}, {0x0?})
	github.com/cosmos/cosmos-sdk@v0.45.15/types/int.go:249 +0x3d
github.com/akash-network/provider/cluster/kube.(*resourcePair).subNLZ(0xc000f31ab0, {{0xc0016dc720?}})
	github.com/akash-network/provider/cluster/kube/resourcetypes.go:67 +0x189
github.com/akash-network/provider/cluster/kube.(*inventory).Adjust(0xc000f8ae30, {0x38a95c0, 0xc00011f6d0})
	github.com/akash-network/provider/cluster/kube/inventory.go:114 +0x4b2
github.com/akash-network/provider/cluster.(*inventoryService).handleRequest(0xc001255c20, {{{0xc001a14690, 0x2c}, 0x41983, 0x1, 0x1}, {0x3899b88, 0xc0001375e0}, 0xc0016ea180}, 0xc00169dc70)
	github.com/akash-network/provider/cluster/inventory.go:412 +0x35f
github.com/akash-network/provider/cluster.(*inventoryService).run(0xc001255c20, {0x38c52a8, 0xc00022ceb0}, {0x518d778?, 0x0, 0x0?})
	github.com/akash-network/provider/cluster/inventory.go:510 +0x75d
created by github.com/akash-network/provider/cluster.newInventoryService
	github.com/akash-network/provider/cluster/inventory.go:129 +0x95b
```

**Comment by troian** [comment]
for @chainzero to check

**Comment by chainzero** [comment]
Issue can be closed as this is no longer encountered in current provider-services version
